### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by valentinvichnal** [CrowdHailer/Ace#2]
Hey @CrowdHailer ,

This is an awesome idea.
I have always wanted to learn how HTTP servers works, creating one with a functional language looks a good way to learn it.

A Roadmap with checkboxes maybe a good idea to make the contribution easy!

**Comment by CrowdHailer** [comment]
I think this is a great idea. If we can come up with a good enough road map with small enough steps it might help people who what to go back through the commit history.

Perhaps instead of laying out the whole process now we should come up with the next 10 steps.
Any additions to the following.

- [x] Minimal echo server 
- [ ] handle client disconnect (thanks for the PR)
- [ ] make the change discussed [here](https://elixirforum.com/t/ace-an-experimental-webserver/1705/6)
- [ ] make proper mix application with tests (TDDing the process from then on) 0.2
- [ ] setup dializer (think we should make the most of having the setup process as an example in vagrant)
- [ ] send message on connection 0.3
- [ ] send server pushed message
- [ ] Have a behaviour callback module
- [ ] handle multiple connections (either fixed or infinite) 0.4
- [ ] Have an acceptor pool

I think that takes us to a working TCP server which should be a point to decide the next steps on the roadmap

**Comment by valentinvichnal** [comment]
These steps looks good to me.
I was thinking to make the multiple connections handle early as possible, but probably this way
the source is going to be more readable.

**Comment by valentinvichnal** [comment]
I suggest you to open a new channel at [Elixir Slack](https://elixir-lang.slack.com/) to get more people working on it.

**Comment by CrowdHailer** [comment]
Sounds good but It might be nice to keep the history. The elixir slack channel looses history after not that long. 
Perhaps a section in the Elixir Forum be good. Perhaps the "learning elixir" category, something like "A road map for building an HTTP server"

Of course comments in github work to but I don't know how to get the elixir community in general to see them

**Comment by valentinvichnal** [comment]
Yes saving the history can be useful for this project, a gitter could work then I think it keeps the messages for an unlimited time.
The forum is good for posting the milestones or asking questions, but only a few people using it compared to the slack channel.

**Comment by CrowdHailer** [comment]
I think might wait until we actually have a few people interested before getting something specifically for ace such as a gitter. My suggestion keep anything that is useful to have as permanent in Github and chat on slack for the rest.

**Comment by CrowdHailer** [comment]
Satisfied I understand the details of `reuseaddr` am moving on to rewriting the application as a mix project

**Comment by CrowdHailer** [comment]
0.5.0 extensions should be

- passing socket information on connection
- having a behaviour
- having the ability to stop the connection at any point.

**Comment by CrowdHailer** [comment]
timeouts would be good to have

**Comment by CrowdHailer** [comment]
next step is motivated by multiple connections, supervision. Property test:-
- conn info
- raw packet echo

**Comment by CrowdHailer** [comment]
I think that once pull request #6 is closed we can be finished with this road map. It might be a new issue to make the HTTP roadmap.

**Comment by CrowdHailer** [comment]
because of my own wrangling with git pr6 is now replaced with #11
